export const queryKeys = {
  LISTINGS: "listings",
  DASHBOARD_LISTINGS: "listings",
  LISTING_BY_ID: "listing-by-id",
  DASHBOARD_LISTING_BY_ID: "listing-by-id",
  ADMIN_USERS: "admin-users",
  ADMIN_LISTINGS: "admin-listings",
  ADMIN_BOOKINGS: "admin-bookings",
  ADMIN_REVIEWS: "admin-reviews",
  ADMIN_DELETE_USER: "admin-delete-user",
  ADMIN_CATEGORIES: "admin-categories",
  ADMIN_DELETE_CATEGORY: "admin-delete-category",
  ADMIN_CATEGORY_BY_ID: "admin-category-by-id",
  HOST_LISTINGS: "host-listings",
  HOST_CALENDAR: "host-calendar",
  HOST_BOOKINGS: "host-bookings",
  HOST_REVIEWS: "host-reviews",
  HOST_DELETE_LISTING: "host-delete-listing",
  HOST_DELETE_BOOKING: "host-delete-booking",
  HOST_CREATE_LISTING: "host-create-listing",
  HOST_CATEGORIES: "host-categories",
  HOST_LISTING_BY_ID: "host-listing-by-id",
  HOST_UPDATE_LISTING: "host-update-listing",
};
